Feat: customersTable
kohiruim/ComputerClubApp pull request #4
Opened 2024-05-21 04:50 UTC by kohiruim

2024-05-22 19:25 UTC, Emptyyw commented on src/features/clientsTable/ui/ClientsTable.tsx
> +  const rows = rowsClientsTable.map((item: UserData) => (
Попробуй это перенести в разметку

2024-05-22 19:25 UTC, Emptyyw commented on src/features/clientsTable/ui/ClientsTable.tsx
> +  const header = headerItems.map(item => (
И это

2024-05-27 17:09 UTC, remadyt requested changes

2024-05-27 17:09 UTC, remadyt commented on src/app/routes/router.tsx
> +    path: "/users",
use enum for paths

2024-05-27 17:09 UTC, remadyt commented on src/features/addClient/model/model.ts
> +const AddClient = async (
why big letter?

2024-05-27 17:09 UTC, remadyt commented on src/features/addClient/model/model.ts
> +const AddClient = async (
maybe use createAsyncThunk

2024-05-27 17:09 UTC, remadyt commented on src/features/addClient/ui/AddClientButton.tsx
> +      email: (value: string) =>
use yup or zod for validations

2024-05-27 17:09 UTC, remadyt commented on src/features/addClient/ui/AddClientButton.tsx
> +        !emailRegex.test(value) ? "только через google почту" : null,
add translates?

2024-05-27 17:09 UTC, remadyt commented on src/features/addClient/ui/AddClientButton.tsx
> +        Добавить клиента
add translates here and all such places

2024-05-27 17:09 UTC, remadyt commented on src/features/clientsTable/ui/ClientsTable.tsx
> +export const ClientsTable = () => {
create reusable component

2024-05-27 17:09 UTC, remadyt commented on src/pages/clientsPage/model/model.ts
> +const search = (
use more informative naming

2024-05-27 17:09 UTC, remadyt commented on src/pages/clientsPage/model/model.ts
> +  if (values.username || values.fullname || values.phone) {
need implement search with firebase, not only in frontend

2024-05-27 17:09 UTC, remadyt commented on src/pages/clientsPage/ui/ClientsPage.tsx
> +            <InputBase
create reusable maskedInput

2024-05-27 17:09 UTC, remadyt commented on src/pages/clientsPage/ui/ClientsPage.tsx
> +            <InputBase
why need login by phone number? in spec - only with google

2024-05-27 17:09 UTC, remadyt commented on src/shared/config/clientsTable.ts
> +export const headerItems = [
translate?

2024-05-27 19:43 UTC, suveiko commented on src/features/addClient/model/model.ts
> +  void AddClient(values, setUsers, closeWindow);
look strange, why you use `void`?

2024-06-04 15:59 UTC, merged